### ISSUE TITLE
Problems with migrations

### ISSUE THREAD

**Issue by betogrun** [groundctrl/shopping_mall#12]
Hi,

I'm facing the following issue when I try to run `$ rails generate shopping_mall:install`

```
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class HatbmToHmt < ActiveRecord::Migration[4.2]
/Users/alberto/projetos/pocs/spree-shared/mystore/db/migrate/20171121170435_hatbm_to_hmt.shopping_mall.rb:2:in `<top (required)>'
/Users/alberto/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/alberto/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class HatbmToHmt < ActiveRecord::Migration[4.2]
/Users/alberto/projetos/pocs/spree-shared/mystore/db/migrate/20171121170435_hatbm_to_hmt.shopping_mall.rb:2:in `<top (required)>'
/Users/alberto/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/alberto/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
Have you seen this error before?

PS: I'm using Rails 5.1.4 and Ruby 2.3.3

Regards,
Alberto

**Comment by dfreerksen** [comment]
Rails 5 requires migrations to have a Rails version number on migrations. This gem hasn't been updated since 2015 so it's not accounting for Rails 5.

Likely your migration will have something like `class HatbmToHmt < ActiveRecord::Migration` or even `class HatbmToHmt < ActiveRecord::Migration[4.2]`. All you should need to do is go into the migration file(s) in your application and change the `4.2` to `5.1` or add `5.1` if it's not there.

It should end up look something like this

```
class HatbmToHmt < ActiveRecord::Migration[5.1]
  ...
end
```

and

```
class CreateSpreeTenants < ActiveRecord::Migration[5.1]
  ...
end
```

**Comment by betogrun** [comment]
Thanks @dfreerksen, it worked! 
I have also deleted HatbToHmt migration since it is no longer necessary.
I replaced:
```
Rails.application.config.middleware.insert_before(
  'ActiveRecord::ConnectionAdapters::ConnectionManagement',
  'Apartment::Elevators::Subdomain'
)
```
to
```
Rails.application.config.middleware.use Apartment::Elevators::Subdomain
```
in initializers/shopping_mall.rb as well.
