### ISSUE TITLE
Prevent Zendesk explosions.

### ISSUE THREAD

**Issue by mattgoucher** [groundctrl/shopping_mall#8]
```
TypeError: Cannot call method 'map' of undefined
    at Request._callback (/Users/mattgoucher/Sites/_cd/v5/admin/controllers/api.js:55:33)
    at Request.self.callback (/Users/mattgoucher/Sites/_cd/v5/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/mattgoucher/Sites/_cd/v5/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/mattgoucher/Sites/_cd/v5/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)
```

**Comment by zachgraves** [comment]
:hankey:

**Comment by vinniefranco** [comment]
:+1:
